### PR TITLE
Add docker config and test script to run the integration tests

### PR DESCRIPTION
**Pull request by jeremi**
I added this code in order to simplify running the integration tests.
For now it is in a docker folder, but let me know if you want it organized in another way.
We should be able to use this to run the integration tests in either Jenkins or Trevis.

Docker build on master of EOS is broken, to test this, there need to have this fix: 
https://github.com/EOSIO/eos/pull/1717

### CODE REVIEW

**Comment by chris-allnutt** [comment]
I like the idea here; will want to get @jcalfee's input before merging tho.

**Comment by jcalfee** [comment]
Very cool.. I'll have a look .. I think we can merge if the integration test can be automated.  I also need to check out how the main eos daemon docker images are being versioned.

**Comment by jcalfee** [comment]
Work-in-progress: https://github.com/EOSIO/eosjs/tree/nuorg-automate-tests-dawn3

**Comment by jcalfee** [comment]
Moved: https://github.com/EOSIO/eosjs/pull/32

**Pull request closed without merging**
