### PR TITLE
add intro page back

### PR DESCRIPTION
**Pull request by lparisc**
## Change Description

Add introduction page back to docs.

## API Changes
- [ ] API Changes

## Documentation Additions
- [x] Documentation Additions

### CODE REVIEW

**Comment by dskvr** [comment]
@lparisc Introduction wasn't removed, it was moved to `index.md` because the `README.md` was not suitable as a splash page.

**Comment by lparisc** [comment]
> @lparisc Introduction wasn't removed, it was moved to `index.md` because the `README.md` was not suitable as a splash page.

Ok I see. I'll fix it then

**Comment by dskvr** [comment]
@lparisc There's nothing to fix. Having both a `README.md` as a splash page and an `introduction.md` that is essentially a splash page doesn't really make sense IMO (that is what it was created for initially, but a miscommunication resulted in the creation of an "Introduction" page.

**Comment by lparisc** [comment]
@dskvr I need to fix the broken link #640 by linking to the index file.

**Comment by bradlhart** [comment]
Not the best solution, but considering @dskvr's notes, maybe the line can be rephrased/removed.

**Comment by dskvr** [comment]
Fix the broken link, don't regress the docs.

**Pull request closed without merging**
