### PR TITLE
add optional sign parameter to transact function

### PR DESCRIPTION
**Pull request by ehnawh**

### CODE REVIEW

**Comment by tbfleming** [comment]
What are you trying to accomplish? After this patch, if sign is false the function does nothing and returns nothing.

**Comment by ehnawh** [comment]
@tbfleming When sign is false, only serializedTransaction without signatures is returned.
It is used to create transaction object for msig(multi sign).

**Comment by tbfleming** [comment]
Ok. I see it now. Please make the following changes:
* `signatures` should be a required member of `PushTransactionArgs`
* For this case, set `signatures` to `[]`
* Remove the extra empty lines
* Bug: `const pushTransactionArgs =` should be `pushTransactionArgs =`

**Comment by ehnawh** [comment]
oh, i got it. i pushed commit about changes

**Pull request merged**
