### PR TITLE
Integrate ESLint and Airbnb JavaScript linting

### PR DESCRIPTION
**Pull request by DanailMinchev**
As discussed in https://github.com/EOSIO/eosjs/issues/268 we would like to integrate ESLint and Airbnb ( https://github.com/airbnb/javascript ).

This PR adds default configuration and initial formatting of the code without any noticeable changes.
Currently the linting is not part of the build: it will be integrated when we customise `.eslintrc.js` to meet the current standard and fix the current code according to this standard.

With this PR we will be able at least auto-format our code according to `Airbnb JavaScript Style Guide`.

Please let me know if you would like to customise `.eslintrc.js` or fix the current files fully.

See commits for more details.

Thanks

### CODE REVIEW

**Comment by chris-allnutt** [comment]
@jcalfee this is the other linting PR.

**Comment by DanailMinchev** [comment]
I've rebased this PR. This is the first PR which adds the default integration, the next one can customise the rules needed.
If you are happy with StandardJS let me know, so I can stop rebasing and close this PR.

**Comment by chris-allnutt** [comment]
@DanailMinchev I’ve messaged @jcalfee to try to decide a direction.  I didn’t expect the standard is pr and I was unaware it was incoming.

**Comment by DanailMinchev** [comment]
@chris-allnutt 

Thanks, I don't mind if we go with the StandardJS PR as Airbnb JavaScript linting needs more work as well

**Pull request closed without merging**
