### PR TITLE
Dawn3

### PR DESCRIPTION
**Pull request by zshchou**
package.json
```json
{
  "name": "eosjs",
  "version": "7.1.2",
  "description": "General purpose library for the EOS blockchain.",
  "main": "lib/index.js",
  "scripts": {
    "test": "mocha --use_strict src/*.test.js",
    "coverage": "nyc --reporter=html npm test",
    "coveralls": "npm run coverage && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls",
    "prepublishOnly": "npm run prepublishOnly_lib && npm run prepublishOnly_test && npm run docs",
    "prepublishOnly_lib": "babel src --out-dir lib",
    "prepublishOnly_test": "mocha --use_strict lib/*.test.js",
    "browserify": "mkdir -p dist && browserify -o dist/eos.js -s Eos lib/index.js",
    "build": "npm run prepublishOnly && npm run browserify",
    "build_browser_test": "mkdir -p dist && browserify -o dist/mocha-test.js src/*.test.js",
    "docs": "jsdoc2md src/format.js > docs/format.md"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/EOSIO/eosjs.git"
  },
  "keywords": [
    "EOS",
    "Blockchain"
  ],
  "author": "",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/EOSIO/eosjs/issues"
  },
  "homepage": "https://github.com/EOSIO/eosjs#readme",
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-stage-2": "^6.24.1",
    "babel-plugin-syntax-async-functions": "^6.13.0",
    "babel-plugin-transform-regenerator": "^6.26.0",
    "browserify": "^16.1.1",
    "coveralls": "^3.0.0",
    "eosjs-keygen": "^1.3.0",
    "jsdoc-to-markdown": "^4.0.1",
    "mocha": "^5.0.5",
    "nyc": "^11.6.0"
  },
  "dependencies": {
    "babel-polyfill": "^6.26.0",
    "binaryen": "^44.0.0",
    "create-hash": "^1.1.3",
    "eosjs-api": "^4.0.0",
    "eosjs-ecc": "^3.0.2",
    "eosjs-json": "^3.0.1",
    "fcbuffer": "^2.1.2"
  },
  "babel": {
    "presets": [
      "env", "stage-2"
    ],
    "plugins": [
      "syntax-async-functions",
      "transform-regenerator"
    ]
  }
}

```

### CODE REVIEW

**Comment by jcalfee** [comment]
dawn3 is not released yet.  Also the only public testnet is dawn2.

**Comment by jcalfee** [comment]
@chris-allnutt what do you think?  This is a good idea but I would like to do this locally in my own branch because of conflicts though so I'll leave this closed.  I'll create a dawn2 branch and replace the dawn3 branch with master.  Also consistent with eosio/eos.

**Comment by chris-allnutt** [comment]
@jcalfee  I agree, this should coincide with the April 6th date the eos team currently has once that's up.  We'll verify against the dawn3 testnet and go from there.

**Comment by jcalfee** [comment]
A simple release table in the README might help too.. We already have github branches to match to npm tags.

**Comment by jcalfee** [comment]
Moved to https://github.com/EOSIO/eosjs/issues/43

**Pull request closed without merging**
